### ISSUE TITLE
where is llvm-config?

### ISSUE THREAD

**Issue by MarchLiu** [Golevka/emacs-clang-complete-async#11]
Sorry for this stupid question. But, em..
I work in 10.8,  XCode 4.5.1. and GNU Emacs 24.1 . When I make this project, the Makefile need llvm-config. But it not in /usr, /usr/local, /opt/local(I use macport) and /Application/Xcode/Contents/Developer/usr.
There is a way build emacs-clang-complete-async without llvm-config ?

**Comment by jaeschliman** [comment]
using http://mxcl.github.com/homebrew/ you can `brew install llvm` and llvm-config will be available.

**Comment by MarchLiu** [comment]
thx @jaeschliman . And I need macport for some resans. So I try to use llvm-config-mp-3.0 replace the llvm-config in Makefile. It run. 
PS. I installed llvm-3.0 and llvm-3.1 by MacPorts. But use the llvm-config-3.1 in this project will failed.

**Comment by zijianyue** [comment]
I'm working on win7,and I've installed LLVM 3.5 from http://llvm.org/releases/3.5.0/LLVM-3.5.0-win32.exe,but llvm-config is not in the installed folder, help please
