### ISSUE TITLE
no completion

### ISSUE THREAD

**Issue by myrgy** [Golevka/emacs-clang-complete-async#13]
Hi, I have no completion of local variables & objects methods.
I use emacs 24.2. Compile with clang 3.1.
I have completion of namespaces & class names.

when I type 
std:: 
completion show vector;
std::vector<int> abc;
but when type ab no completion "abc" is appear & after
type: abc.
no methods.
Thanks.

**Comment by myrgy** [comment]
On Nov 2, 2012, at 4:48 PM, Golevka wrote:

> Maybe you want to try std::vector abc; instead
> 
> —
> Reply to this email directly or view it on GitHub.

typename completion work
\

no completion for variables.

and methods.

**Comment by myrgy** [comment]
Could you help me to solve my problem with completion?

**Comment by Golevka** [comment]
I don't know if I can fix this, maybe this way will help: You can specify the location of your library headers explicitly to guide clang to look for those symbols, this is a code fragment taken from my personal emacs configuration file:
;; ac-source-gtags(setq ac-clang-flags      (mapcar (lambda (item)(concat "-I" item))              (split-string               " /usr/include/c++/clang/3.0/include /usr/include/c++/4.7.0 /usr/include/c++/4.7.0/i686-pc-linux-gnu /usr/include/c++/4.7.0/backward /usr/lib/gcc/i686-pc-linux-gnu/4.7.0/include /usr/local/include /usr/lib/gcc/i686-pc-linux-gnu/4.7.0/include-fixed /usr/include"               )))
where the argument to split-string should be modified to fit your site, it can be obtained by running echo "" | g++ -v -x c++ -E - , https://github.com/brianjcj/auto-complete-clang explained this command in great detail. 
SincerelyGolevka
Date: Mon, 5 Nov 2012 09:54:47 -0800

**Comment by myrgy** [comment]
For me it works - sinse closed
