### ISSUE TITLE
Crash after clang_codeCompleteAt returned NULL

### ISSUE THREAD

**Issue by ghost** [Golevka/emacs-clang-complete-async#16]
clang_codeCompleteAt returns NULL on completion failure.
After call to completion_codeCompleteAt, res == NULL.
Further usage of the NULL pointer leads to crash on line: clang_sortCodeCompletionResults(res->Results, res->NumResults);

**Comment by Golevka** [comment]
Mine, tried to fix this problem in commit 516ab72ded22009d6613350850fda11141f907ac and I hope it could work.
