### ISSUE TITLE
Please add a version tag

### ISSUE THREAD

**Issue by yasuyk** [Golevka/emacs-clang-complete-async#34]
Hi,

I added a [MELPA](http://melpa.milkbox.net/) recipe so that easily-installable packages of `auto-complete-clang-async.el` are available.

Next, I'm adding a [Homebrew](https://github.com/mxcl/homebrew) formula so that `clang-complete` are available effortlessly on Mac OS X. But it is pending, so Homebrew formula needs versioned download (See [#19499](https://github.com/mxcl/homebrew/pull/19449)).

For the above reason, please add a version tag?

Cheers!

--Yasuyuki

**Comment by Golevka** [comment]
v0.5 was added as my 1st tag. `v0.5 - 0.5 is the first version`

**Comment by yasuyk** [comment]
Thanks!
