### ISSUE TITLE
Mac OS X w/ Xcode 5.1.1: error: unknown type name 'FILE'

### ISSUE THREAD

**Issue by causlayer** [Golevka/emacs-clang-complete-async#68]
I've installed llvm using brew:
brew install --with-clang --all-targets --rtti --universal --jit llvm
brew link llvm --force
error:
cc -std=c99 -I/usr/local/Cellar/llvm/3.4/include  -D_DEBUG -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -O3  -fno-common -Wall -Wextra -pedantic -O3 -I./src   -c -o src/obj/completion_serv.o ./src/completion_serv.c
In file included from ./src/completion_serv.c:3:
./src/completion.h:57:75: error: unknown type name 'FILE'
void completion_printCompletionLine(CXCompletionString completion_string, FIL...
                                                                          ^
./src/completion.h:60:72: error: unknown type name 'FILE'
void completion_printCodeCompletionResults(CXCodeCompleteResults _res, FILE *...
                                                                       ^
2 errors generated.
make: *_\* [src/obj/completion_serv.o] Error 1

How can I install the type name 'FILE' ?

**Comment by Sarcasm** [comment]
#56

**Comment by causlayer** [comment]
thx
