### ISSUE TITLE
Add this repo to the auto-complete organization

### ISSUE THREAD

**Issue by monsanto** [Golevka/emacs-clang-complete-async#7]
Hi there, 

I'm collecting the various sources for AC under the newly minted auto-complete organization. We would like to make this source the "official" clang source and make the canonical repo at the auto-complete organization. You would obviously have full access to the repo.

If you don't like that idea, we can also just mirror the repo.

**Comment by Golevka** [comment]
Appreciated to have my repo being invited to such a wonderful organization, that is awesome so let's go ahead.

**Comment by monsanto** [comment]
Great. I'll have some time to work on this in 2 or 3 days (grad school obligations atm).

I'd like to split out the yasnippet support into something modular. For instance, I use similar functionality in https://github.com/monsanto/auto-complete-auctex, the new semantic source will have support for yasnippet, and I'd like to hook up something like this as well for Python. See https://github.com/capitaomorte/yasnippet/issues/295 for related discussion
